name: docker-build
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout built branch
      uses: actions/checkout@v2
    - name: Build 
      run: |
        docker pull ghcr.io/maison-de-la-simulation/ddc/test_env || true
        docker build \
          --cache-from ghcr.io/maison-de-la-simulation/ddc/test_env \
          -t ghcr.io/maison-de-la-simulation/ddc/test_env \
          -t ghcr.io/maison-de-la-simulation/ddc/test_env:${GITHUB_SHA:0:7} \
          test_env
    - name: Publish
      if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/maison-de-la-simulation/ddc/test_env
        docker push ghcr.io/maison-de-la-simulation/ddc/test_env:${GITHUB_SHA:0:7}
