name: pages
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout built branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - name: Install deps
      run: |
        sudo apt-get install -y \
            doxygen \
            doxygen-latex \
            graphviz \
            texlive
    - name: Build site
      run: |
        cmake -DBUILD_DOCUMENTATION=ON -DDDC_BUILD_PDI_WRAPPER=OFF .
        make doc
    - name: Publish site
      if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      run: |
        git worktree add -B gh-pages public remotes/origin/gh-pages
        find public -mindepth 1 -maxdepth 1 '!' -name .git -exec rm -rf '{}' '+'
        mv docs/html/* public/
        git -C public config user.name "${GITHUB_ACTOR}"
        git -C public config user.email "${GITHUB_ACTOR}@noreply.example.com"
        git -C public add -A .
        git -C public commit -a -m "Update to match ${GITHUB_SHA} by ${GITHUB_EVENT_NAME} ${GITHUB_RUN_NUMBER}" || true
        git -C public push
