name: test
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  pages:
    runs-on: ubuntu-latest
    container:
      image: jbigot/voicexx_env
    steps:
    - name: Checkout built branch
      uses: actions/checkout@v2
      submodules: true
    - name: Build 
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_FLAGS=-Wall -DBUILD_BENCHMARKS=ON -DCMAKE_BUILD_TYPE=Release ..
        make -j 2 VERBOSE=1
        ctest -j 2 --output-on-failure --timeout 5 --output-junit tests.xml
