name: test
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout built branch
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build 
      run: |
        cat<<-EOF > run.sh
          set -xe
          pwd
          id
          ls -l .
          touch tst.tst
          cmake -DCMAKE_CXX_FLAGS=-Wall -DBUILD_BENCHMARKS=ON -DCMAKE_BUILD_TYPE=Release /src
          make -j 2 VERBOSE=1
          ctest -j 2 --output-on-failure --timeout 5 --output-junit tests.xml
        EOF
        docker run -v ${PWD}:/src:ro ghcr.io/maison-de-la-simulation/ddc/test_env bash /src/run.sh
